export const Recipes = [
    {
      name: "Spaghetti Carbonara",
      ingredients: [
        "200g spaghetti",
        "100g pancetta",
        "2 large eggs",
        "50g pecorino cheese",
        "50g parmesan cheese",
        "2 cloves garlic",
        "Salt and black pepper",
      ],
      instructions: [
        "Boil the spaghetti in salted water.",
        "Fry the pancetta with the garlic until crisp.",
        "Beat the eggs and mix with the cheeses.",
        "Drain the spaghetti and combine with the pancetta.",
        "Remove from heat and mix in the egg and cheese mixture.",
        "Season with salt and pepper to taste.",
      ],
    },
    {
      name: "Chicken Stir Fry",
      ingredients: [
        "2 chicken breasts, sliced",
        "1 red bell pepper, sliced",
        "1 green bell pepper, sliced",
        "1 onion, sliced",
        "2 cloves garlic, minced",
        "2 tbsp soy sauce",
        "1 tbsp oyster sauce",
        "1 tbsp vegetable oil",
        "Salt and pepper to taste",
      ],
      instructions: [
        "Heat oil in a pan and cook the chicken until browned.",
        "Add the garlic and cook for another minute.",
        "Add the bell peppers and onion, and stir fry for 5-7 minutes.",
        "Mix in the soy sauce and oyster sauce.",
        "Season with salt and pepper to taste.",
        "Serve hot with rice or noodles.",
      ],
    },
    {
      name: "Vegetable Curry",
      ingredients: [
        "1 tbsp vegetable oil",
        "1 onion, chopped",
        "2 cloves garlic, minced",
        "1 tbsp ginger, minced",
        "2 tbsp curry powder",
        "1 can coconut milk",
        "1 can diced tomatoes",
        "1 cup vegetable broth",
        "2 potatoes, diced",
        "2 carrots, sliced",
        "1 bell pepper, chopped",
        "Salt and pepper to taste",
      ],
      instructions: [
        "Heat oil in a pot and sauté the onion, garlic, and ginger until fragrant.",
        "Add the curry powder and cook for another minute.",
        "Pour in the coconut milk, tomatoes, and vegetable broth.",
        "Add the potatoes, carrots, and bell pepper.",
        "Bring to a boil, then reduce heat and simmer until vegetables are tender.",
        "Season with salt and pepper to taste.",
        "Serve hot with rice or naan.",
      ],
    },
    {
      name: "Pancakes",
      ingredients: [
        "1 cup flour",
        "1 tbsp sugar",
        "1 tsp baking powder",
        "1/2 tsp baking soda",
        "1/2 tsp salt",
        "1 cup buttermilk",
        "1 egg",
        "2 tbsp melted butter",
        "Butter or oil for cooking",
      ],
      instructions: [
        "Mix the dry ingredients in a bowl.",
        "In another bowl, whisk together the buttermilk, egg, and melted butter.",
        "Combine the wet and dry ingredients and stir until just mixed.",
        "Heat a griddle or pan and grease with butter or oil.",
        "Pour batter onto the griddle and cook until bubbles form on the surface.",
        "Flip and cook until the other side is golden brown.",
        "Serve with syrup, butter, or your favorite toppings.",
      ],
    },
    {
      name: "Caesar Salad",
      ingredients: [
        "1 romaine lettuce, chopped",
        "1/2 cup croutons",
        "1/4 cup grated parmesan cheese",
        "1/3 cup Caesar dressing",
        "1 clove garlic, minced",
        "1 tbsp lemon juice",
        "Salt and pepper to taste",
      ],
      instructions: [
        "In a large bowl, combine the chopped romaine, croutons, and grated parmesan.",
        "In a small bowl, mix the Caesar dressing with the minced garlic and lemon juice.",
        "Pour the dressing over the salad and toss to coat.",
        "Season with salt and pepper to taste.",
        "Serve immediately.",
      ],
    },
  ];
  